language: python
matrix:
  include:
    - python: "2.7"
      env: TEST_SUITE=suite_2_7
    - python: "3.2"
      env: TEST_SUITE=suite_3_2
    - python: "3.3"
      env: TEST_SUITE=suite_3_3
    - python: "3.4"
      env: TEST_SUITE=suite_3_4
    - python: "pypy"
      env: TEST_SUITE=suite_pypy
install:
  - if [[ $TEST_SUITE == suite_3_4 ]]; then
        pip install sphinx;
    fi;
  - pip install coverage

  - mkdir tmp && cd tmp
  # start bibtex_cleanup_parser dependency
  - wget https://github.com/njalerikson/bibtex_cleanup_parser/archive/master.tar.gz -O bibtexparser.tar.gz
  - tar -xvf bibtexparser.tar.gz && cd bibtexparser
  - python setup.py install
  - cd ..
  # end bibtex_cleanup_parser dependency
  
  - python setup.py install
script:
  - nosetests --with-coverage  --cover-erase --cover-package=bibtex_merger
  # - if [[ $TEST_SUITE == suite_3_4 ]]; then
  #       cd docs;
  #       make html;
  #   fi;

after_success:
  - pip install coveralls
  - coveralls