language: python
matrix:
  include:
    - python: "2.7"
      env: TEST_SUITE=suite_2_7
    - python: "3.2"
      env: TEST_SUITE=suite_3_2
    - python: "3.3"
      env: TEST_SUITE=suite_3_3
    - python: "3.4"
      env: TEST_SUITE=suite_3_4
    - python: "pypy"
      env: TEST_SUITE=suite_pypy
install:
  - if [[ $TEST_SUITE == suite_3_4 ]]; then
        pip install sphinx;
    fi;
  - pip install coverage
  - cd bibtex_merger/Levenshtein && python setup.py install && cd ../..
  - cd bibtex_merger/Fuzzy && python setup.py install && ../..
  # Install gmpy2 dependencies
  - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
  - tar xzvf mpc-1.0.2.tar.gz
  - pushd mpc-1.0.2
  - ./configure
  - make
  - sudo make install
  - popd
  # End install gmpy2 dependencies
  # - cd bibtex_merger/gmpy2 && python setup.py install
  # - cd ../..
  - pip install gmpy2
  # - pip install sklearn
  # - pip install numpy
  - python setup.py install
script:
  - nosetests --with-coverage  --cover-erase --cover-package=src
  # - if [[ $TEST_SUITE == suite_3_4 ]]; then
  #       cd docs;
  #       make html;
  #   fi;

after_success:
  - pip install coveralls
  - coveralls